data:extend(
{
	{
		type = "fluid",
		name = "natural-gas",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.90, g=0.89, b=0.89},
		flow_color = {r=0.90, g=0.89, b=0.89},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/natural-gas.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[natural-gas]"
	},
	{
		type = "fluid",
		name = "methane",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.76, g=0.76, b=0.76},
		flow_color = {r=0.76, g=0.76, b=0.76},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/methane.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[methane]"
	},
	{
		type = "fluid",
		name = "nitrogen",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.84, g=0.84, b=0.84},
		flow_color = {r=0.86, g=0.86, b=0.84},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/nitrogen.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[nitrogen]"
	},
	{
		type = "fluid",
		name = "potassium-nitrate",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.99, g=0.99, b=0.99},
		flow_color = {r=0.99, g=0.99, b=0.99},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/potassium-nitrate.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[potassium-nitrate]"
	},
	{
		type = "fluid",
		name = "nitric-acid",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.92, g=0.93, b=0.63},
		flow_color = {r=0.92, g=0.93, b=0.63},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/nitric-acid.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[nitric-acid]"
	},
	{
		type = "fluid",
		name = "hydrochloric-acid",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.92, g=0.93, b=0.60},
		flow_color = {r=0.92, g=0.93, b=0.60},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/hydrochloric-acid.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[hydrochloric-acid]"
	},
	{
		type = "fluid",
		name = "methanol",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.27, g=0.28, b=0.22},
		flow_color = {r=0.27, g=0.28, b=0.22},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/methanol.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[methanol]"
	},
	{
		type = "fluid",
		name = "carbon-monoxide",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.49, g=0.48, b=0.48},
		flow_color = {r=0.49, g=0.48, b=0.48},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/carbon-monoxide.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[carbon-monoxide]"
	},
	{
		type = "fluid",
		name = "carbon-dioxide",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.47, g=0.49, b=0.49},
		flow_color = {r=0.47, g=0.49, b=0.49},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/carbon-dioxide.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[carbon-dioxide]"
	},
	{
		type = "fluid",
		name = "hydrogen",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.49, g=0.54, b=0.71},
		flow_color = {r=0.49, g=0.54, b=0.71},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/hydrogen.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[hydrogen]"
	},
	{
		type = "fluid",
		name = "oxygen",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.41, g=0.54, b=0.95},
		flow_color = {r=0.41, g=0.54, b=0.95},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/oxygen.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[oxygen]"
	},
	{
		type = "fluid",
		name = "syngas",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.26, g=0.27, b=0.10},
		flow_color = {r=0.26, g=0.27, b=0.10},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/syngas.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[syngas]"
	},
	{
		type = "fluid",
		name = "clean-syngas",
		default_temperature = 15,
		heat_capacity = "1KJ",
		base_color = {r=0.27, g=0.28, b=0.11},
		flow_color = {r=0.27, g=0.28, b=0.11},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/clean-syngas.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[clean-syngas]"
	},
	{
		type = "fluid",
		name = "slag",
		default_temperature = 1000,
		heat_capacity = "5000KJ",
		base_color = {r=0.81, g=0.06, b=0.12},
		flow_color = {r=0.81, g=0.06, b=0.12},
		max_temperature = 2000,
		icon = "__EnchantedIndustries__/graphics/icons/slag.png",
        icon_size = 32,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[slag]"
	},
	{
		type = "fluid",
		name = "aqua-regia",
		default_temperature = 25,
		heat_capacity = "1KJ",
		base_color = {r=0.90, g=0.70, b=0.15},
		flow_color = {r=0.90, g=0.70, b=0.15},
		max_temperature = 100,
		icon = "__EnchantedIndustries__/graphics/icons/aqua-regia.png",
        icon_size = 64,
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "a[fluid]-b[aqua-regia]"
	},
})